name: flutter_sample_bloc
description: A new Flutter project.

publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  # flutter defaults
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2

  #riverpod state management
  flutter_riverpod: ^2.0.2
  
  # svg helper
  flutter_svg: ^0.22.0

  # helper to load info from .env files
  flutter_dotenv: ^5.0.2

  #caching image
  cached_network_image: ^3.2.1

  #calculation time ago
  timeago: ^3.3.0

  #launching urls
  url_launcher: ^6.1.5

  #reactive programming
  rxdart: ^0.27.5

  # app modules
  news_repository:
    path: ./packages/news_repository
  api_client:
    path: ./packages/api_client
  

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/
    - assets/fonts/
    - .env
